const PAGE_WIDTH = 1242;
const PAGE_HEIGHT = 2208;
const REACTOR_WIDTH = 600;
const REACTOR_HEIGHT = 1000;
const REACTOR_X = (PAGE_WIDTH - REACTOR_WIDTH) / 2;
const REACTOR_Y = (PAGE_HEIGHT - REACTOR_HEIGHT) / 2;

export default {
  PAGE_WIDTH,
  PAGE_HEIGHT,
  REACTOR_WIDTH,
  REACTOR_HEIGHT,
  REACTOR_X,
  REACTOR_Y,
};
