const REACTOR_WIDTH = 120;
const REACTOR_HEIGHT = 280;
const SPEED_FACTOR = 2;
const ROTATION_SPEED_FACTOR = 2;
const INTRO_PAGE_SEP_MARGIN = 80;
const INTRO_PAGE_BODY_HEIGHT = 348;

export default {
  REACTOR_WIDTH,
  REACTOR_HEIGHT,
  SPEED_FACTOR,
  ROTATION_SPEED_FACTOR,
  INTRO_PAGE_SEP_MARGIN,
  INTRO_PAGE_BODY_HEIGHT,
};
